package com.rustedwax.app.enrich

import android.content.Context
import org.json.JSONObject
import java.io.File

class FactsCache(context: Context, private val maxEntries: Int = 200) {

	private val dir = File(context.filesDir, "enrich").apply { mkdirs() }

	/**
	 * Memory front for the disk store. Exists so the Now-tab preview — which
	 * re-renders every second — can ask for facts without touching disk after
	 * the first hit.
	 */
	private val memory = java.util.concurrent.ConcurrentHashMap<String, VideoFacts>()

	fun get(videoId: String): VideoFacts? {
		memory[videoId]?.let { return it }
		val file = fileFor(videoId) ?: return null
		if (!file.exists()) return null
		return runCatching {
			decode(videoId, file.readText())
		}.getOrNull()?.also { memory[it.videoId] = it }
	}

	fun put(facts: VideoFacts) {
		memory[facts.videoId] = facts
		val file = fileFor(facts.videoId) ?: return
		runCatching {
			file.writeText(encode(facts))
			evictIfNeeded()
		}
	}

	/**
	 * Video ids are `[A-Za-z0-9_-]{11}`, but this builds a file path, so it is
	 * validated rather than trusted — an id arriving from a scraped address bar
	 * has no business containing a path separator.
	 */
	private fun fileFor(videoId: String): File? =
		if (VIDEO_ID.matches(videoId)) File(dir, "$videoId.json") else null

	private fun evictIfNeeded() {
		val files = dir.listFiles() ?: return
		if (files.size <= maxEntries) return
		files.sortedBy { it.lastModified() }
			.take(files.size - maxEntries)
			.forEach { it.delete() }
	}

	internal companion object {
		val VIDEO_ID = Regex("""[A-Za-z0-9_-]{11}""")

		/** Pure codec so schema/legacy behavior is regression-testable without Android. */
		fun decode(videoId: String, json: String): VideoFacts? {
			val o = JSONObject(json)
			// These fields changed the meaning of an otherwise valid legacy row.
			// Missing artist-credit provenance remains a descriptive unknown; shared
			// YouTube/Brave cache rows need not be discarded because it is not a gate.
			if (!o.has("watchPageResolved") || !o.has("ownerHandle")) return null
			return VideoFacts(
				videoId = videoId,
				title = o.optStringOrNull("title"),
				author = o.optStringOrNull("author"),
				ownerHandle = o.optStringOrNull("ownerHandle"),
				category = o.optStringOrNull("category"),
				lengthSeconds = o.optLong("lengthSeconds").takeIf { it > 0 },
				isUnlisted = o.optBooleanOrNull("isUnlisted"),
				isCrawlable = o.optBooleanOrNull("isCrawlable"),
				watchPageResolved = o.optBoolean("watchPageResolved"),
				originalArtist = o.optStringOrNull("originalArtist"),
				watchPageArtistCredit = o.optStringOrNull("watchPageArtistCredit"),
				originalTitle = o.optStringOrNull("originalTitle"),
				autoGenerated = o.optBoolean("autoGenerated"),
				musicVideoType = o.optStringOrNull("musicVideoType"),
				album = o.optStringOrNull("album"),
			)
		}

		fun encode(facts: VideoFacts): String = JSONObject()
			.putOpt("title", facts.title)
			.putOpt("author", facts.author)
			// Write an explicit null so current missing evidence differs from legacy.
			.put("ownerHandle", facts.ownerHandle ?: JSONObject.NULL)
			.putOpt("category", facts.category)
			.putOpt("lengthSeconds", facts.lengthSeconds)
			.putOpt("isUnlisted", facts.isUnlisted)
			.putOpt("isCrawlable", facts.isCrawlable)
			.put("watchPageResolved", facts.watchPageResolved)
			.putOpt("originalArtist", facts.originalArtist)
			// An explicit null records that current resolution found no independent
			// watch-page credit; legacy absence decodes to the same safe unknown.
			.put("watchPageArtistCredit", facts.watchPageArtistCredit ?: JSONObject.NULL)
			.putOpt("originalTitle", facts.originalTitle)
			.put("autoGenerated", facts.autoGenerated)
			.putOpt("musicVideoType", facts.musicVideoType)
			.putOpt("album", facts.album)
			.toString()

		private fun JSONObject.optStringOrNull(key: String): String? =
			if (isNull(key)) null else optString(key).ifBlank { null }

		private fun JSONObject.optBooleanOrNull(key: String): Boolean? =
			if (has(key) && !isNull(key)) optBoolean(key) else null
	}
}
